
project:
  type: website
  output-dir: docs
  # render:
  #   - "index.qmd"
  #   - "content/project.qmd"
  #   - "content/team/index.qmd"
  #   - "content/impressum.qmd"
  resources:
    - assets/**
lang: de


website:
  title: "Argumentkartierung"
  description: "Kontroversen begleiten mit Argumentkarten"
  site-url: https://kobekarten.github.io/
  favicon: ""

  navbar:
    background: primary
    pinned: true
    search: true
    left:
      - text: "Das Projekt"
        href: content/project.qmd
      - text: "Das Team"
        href: content/team/index.qmd
      # - text: "Themen & Bausteine"
      #   menu:
      #     - text: "Baukasten Argumentkartierung"
      #       href: content/baukasten_argumentkartierung.qmd
      #     - text: "Grundlagenseminare"
      #       href: content/grundlagenseminare.qmd

  page-footer:
    left: 
      - "Argumentkartierung"
    center: |
      Gefördert von <a href="https://stiftung-hochschullehre.de" target="_blank" rel="noopener" class="footer-logo-link"><img src="/content/images/Logo_Stiftung_Hochschullehre.svg" alt="Stiftung Hochschullehre" class="footer-logo-svg"></a> <a href="https://hhu.de" target="_blank" rel="noopener" class="footer-logo-png-link"><img src="/content/images/hhu_logo_transparent.png" alt="HHU" class="footer-logo-png"></a>
    right:
      - text: "Datenschutz"
        href: https://www.hhu.de/datenschutzerklaerung
      - text: "Impressum"
        href: /content/impressum.html
      - text: "Hosted auf Github"
        href: https://github.com/argumentkartierung/argumentkartierung.github.io
      - text: "Gebaut mit Quarto"
        href: https://quarto.org

format:
  html:
    css:
      - assets/styles/menu_anim.css
      - assets/styles/custom.css    #intended: will be overwritten/generated by the workflow based on `custom.scss`
    respect-user-color-scheme: true
    template-partials:
      - assets/partials/title-block.html
    theme:
      light: [flatly, assets/styles/custom.scss]
      dark: [darkly, assets/styles/custom.scss]
    toc-depth: 3
    argdown:
      mode: web-component
      sourceHighlighter: web-component
      config: argdown.config.json
  pdf:
    documentclass: article
    pdf-engine-opt: "-shell-escape"
    papersize: a4
    toc: false
    include-in-header: assets/latex/_handout-packages.tex
    template-partials:
      - assets/latex/before-body.tex
    syntax-definitions:
      - assets/pandoc/argdown.xml
    syntax-highlighting: assets/pandoc/argdown.theme

execute:
  freeze: auto

filters:
  - ./node_modules/.bin/argdown-filter
  
argdown:
  mode: inline
  format: svg
  config: argdown.config.json
