---
title: "Das Projekt"
toc: true
format:
  html: default
---

Der konstruktive Umgang mit Kontroversen ist eine wichtige Qualifikation für Studierende. In Kontroversen stehen verschiedene Thesen und Behauptungen zur Debatte, die durch Argumente begründet und kritisiert werden – je nach Thema unter Berufung auf Werte, empirische Daten oder andere Quellen. Die argumentativen Bezüge zwischen Argumenten und Thesen lassen sich jedoch nicht erschöpfend anhand ihrer Strukturierung in Pro-Kontra-Listen analysieren, da sich Argumente auch aufeinander beziehen können. So sind Argumente beispielsweise selbst Einwänden ausgesetzt, die wiederum entkräftet werden können. Zur Analyse und Darstellung komplexer Argumentbeziehungen wird in Philosophie, Argumentationstheorie und Critical Thinking die Methode der Argumentkartierung (Argument Mapping) verwendet, die in diesem Projekt weiterentwickelt werden soll.

## Argumentkartierung {#methoden}

In Argumentkarten werden die argumentativen Bezüge zwischen Argumenten und Thesen durch grüne Pfeile für Begründungen und rote Pfeile für Kritik dargestellt. Thesen werden durch weiß hinterlegte Kästen dargestellt und können durch Argumente begründet oder kritisiert werden. Argumente werden als farblich hinterlegte Kästen dargestellt. Die interne Struktur von Argumenten (ihre Prämissen und die dadurch begründete Konklusion) legt die argumentativen Beziehungen zwischen den Argumenten und den Thesen fest. 

Indem solche Argumentkarten entworfen, im Dialog mit den Beteiligten evaluiert und überarbeitet werden, lassen sich komplexe Kontroversen besser überblicken und wesentliche Beiträge zur Lösungsfindung erarbeiten.

## Argdown

Argumentkarten können mit unterschiedlichen Anwendungen erstellt werden. Im Prinzip reichen Papier und Stift. In diesem Projekt arbeiten wir mit [Argdown](https://argdown.org/), sodass Argumentkarten wie diese hier erstellt werden können: 

```argdown-map
[Hauptthese]: Hauptthese, die durch Argumente begründet oder kritisiert wird. #pro
    + <1. Argument>: Argument, das die Hauptthese begründet. #pro
    + <2. Argument>: Ein weiteres Argument, das die Hauptthese begründet. #pro
    - <3. Argument (Einwand)>: Argument, das einen Einwand gegen die Hauptthese formuliert. #con
        - <4. Argument (Entkräftung)>: Argument, das den Einwand entkräftet. #pro
```

[Argdown](https://argdown.org/) ist eine einfache, textbasierte Sprache, die von [Markdown](https://daringfireball.net/projects/markdown/) inspiriert und für die Erstellung von Argumentkarten optimiert ist. Mit Argdown lassen sich Argumentkarten kollaborativ erstellen und in verschiedene redaktionelle Prozesse einbinden. Argdown wird bereits in verschiedenen Tools unterstützt (z. B. in [VS Code](https://marketplace.visualstudio.com/items?itemName=christianvoigt.argdown-vscode) und [Obsidian](https://community.obsidian.md/plugins/obsidian-argdown-plugin)).


## Projektziele {#ziele}

In diesem Projekt werden Lehrinhalte und Kurskonzepte entwickelt, mit denen Studierende die Methode der Argumentkartierung erlernen, um Kontroversen konstruktiv begleiten zu können. Sie üben sich darin, relevante Argumente und deren Beziehungen zueinander zu analysieren, sie angemessen darzustellen und diese Darstellungen konstruktiv in den weiteren Verständigungs- und Lösungsprozess einzubringen. 

Dazu werden im Projekt allgemeine und transferierbare Open Educational Resources (OERs) sowie spezifische Konzepte für deren Einsatz in verschiedenen Lehr- und Lernformaten entwickelt. Während der Projektlaufzeit werden vier Kurskonzepte entwickelt und erprobt:

1. **Grundlagenseminare:** Typischerweise werden in Logik und Argumentationstheorie einzelne Argumente analysiert. Durch die Grundlagenseminare lernen Philosophie-Studierende schon zu Beginn ihres Studiums die Methode der Argumentkartierung kennen, mit der sie komplexe Zusammenhänge zwischen mehreren Argumenten analysieren können.
2. **Forschungsdebatten-Seminare:** In fortgeschrittenen Seminaren wenden Philosophie-Studierende die Methode der Argumentkartierung auf komplexe philosophische Debatten an, um sich kritisch mit ihnen auseinanderzusetzen und eigene Positionen systematisch zu entwickeln. Nach der gemeinsamen Rekonstruktion eines Kerns kartieren Studierende eigenständig in Arbeitsgruppen weitere Teile der Debatte.
3.  **Seminare für Studierende aller Fächer:** Seminare zu fächerübergreifenden Themen (z.B. technische, rechtliche und ethische Aspekte im Umgang mit KI) werden für Studierende aller Fächer angeboten. Hier werden neben der Methode der Argumentkartierung natürlich auch Grundlagen der Argumentanalyse vermittelt. Im Zentrum steht das fächerübergreifende Potenzial dieser Methode.
4. **Bürger:innenbeteiligungs-Seminare:** Studierende setzen die Methode der Argumentkartierung zur konstruktiven Begleitung aktueller öffentlicher Debatten ein. Anknüpfend an bewährte Nutzungsformen von Argumentkarten in der Bürger:innenbeteiligung werden externe Interessierte im Sinne der partizipativen Wissenschaftskommunikation eingebunden.
